services:
  db:
    image: mysql:8.0
    container_name: odin-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: odinpass
      MYSQL_DATABASE: odin
      MYSQL_USER: odinuser
      MYSQL_PASSWORD: odinpass
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: odin-backend
    restart: always
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: odin-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: odinuser
      PMA_PASSWORD: odinpass
    ports:
      - "8081:80"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: odin-frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true 
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data: {}
